[package]
name = "raccoon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
hex = "0.4.3"
object = { version = "0.36.0", features = ["write"] }
iced-x86 = { version = "1.21.0", features = ["code_asm"] }
